### ISSUE TITLE
feat(o365/get_user): needs to return more/all user properties.

### ISSUE THREAD

**Issue by w-le** [PlaceOS/calendar#11]
https://github.com/PlaceOS/calendar/blob/9a56363ce0bd42f8bccf7cdbcecde6ed787da951/src/office365.cr#L22

Currently when testing with an o365 tenant the only properties returned are id, name, email.
Current and future apps will need more fields returned such as:
- jobTitle
- department
- businessPhones
- employeeId
- city
- country

all available user fields:
https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0

I think we should create a msgraph<>google user > placeOS user properties mapping similar to the one for events, to decide which properties are returned by default and how they align across the two directory types. https://docs.google.com/spreadsheets/d/1MwTBFlB_BL-ZjQ_Gl2PzEqyUJNEstIywgW69XOTNOog/edit#gid=0

The user get/list functions should also allow optional requesting of non-default properties to return, similar to [MSGraph's $select](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http#example-3-users-request-using-select)

**Comment by stakach** [comment]
comparison
Google: https://developers.google.com/admin-sdk/directory/reference/rest/v1/users#User
Office: https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0

Makes sense to do this for get user - I think it's super cut down as the whole model isn't returned when grabbing users in a group etc
