### ISSUE TITLE
MS Teams online meeting link is enabled by DEFAULT - shouldn't the default be disabled?

### ISSUE THREAD

**Issue by w-le** [PlaceOS/calendar#13]
https://github.com/PlaceOS/calendar/blob/ab8babafca01954545694da5cc116108a7af4eb3/src/office365.cr#L3-L9

Currently the above means that placeos/calendar clients defined like this will always have the MS Teams link in ALL events, with no way to disable/enable it on per event basis AFAIK.

I believe a better default would be to have the MS Teams link DISABLED, and then the placeos/calendar `create_event()` method should have an optional param for allowing an OnlineMeetingLink to be added, and another optional param for specifying which onlinemeeting TYPE (should use default if none is specified).

**Comment by stakach** [comment]
Technically you can provide the conference type via the configuration
https://github.com/PlaceOS/calendar/blob/master/src/place_calendar.cr#L37

So we just need to update this driver, for instance and same with the Staff API to support the conference type param
https://github.com/PlaceOS/drivers/blob/master/drivers/place/calendar.cr#L41-L53

but yeah, currently no way to disable on a per-event level

**Comment by stakach** [comment]
fixed in 0ecd9dedeca9f4b57fdd645898e9d58b39953b4a
