### ISSUE TITLE
o365 batch request only supports 20 requests and will error if using more

### ISSUE THREAD

**Issue by pkheav** [PlaceOS/calendar#14]
This is buried in the graph api docs but mentioned here https://docs.microsoft.com/en-us/graph/known-issues#limit-on-batch-size

I could reproduce this by creating a level zone with more than 20 bookable systems which the  get request to `/api/staff/v1/events?zone_ids=zone-id&period_start=1618873200&period_end=1618959599` 

returns `{
  "error": {
    "code": "BadRequest",
    "message": "Number of requests inside batch exceed the limit.",
    "innerError": {
      "date": "2021-04-20T10:32:35",
      "request-id": "6671ba03-f865-443f-84a6-0feb0bab9d36",
      "client-request-id": "6671ba03-f865-443f-84a6-0feb0bab9d36"
    }
  }
} 
 Bad Request (PlaceCalendar::Exception)
  from src/lib/place_calendar/src/office365.cr:321:7 in 'handle_office365_exception'
  from src/lib/place_calendar/src/office365.cr:275:7 in 'batch'
  from src/lib/place_calendar/src/place_calendar.cr:23:5 in 'batch'
  from src/src/controllers/events.cr:31:5 in 'index'
  from src/src/controllers/events.cr:1:1 in 'get__api_staff_v1_events_'
  from src/src/controllers/events.cr:723:9 in '~proc5Proc(HTTP::Server::Context, Bool, HTTP::Server::Context)'
  from usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/lib/action-controller/src/action-controller/log_handler.cr:57:13 in 'call'
  from usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/lib/action-controller/src/action-controller/error_handler.cr:68:5 in 'call'
  from usr/share/crystal/src/http/server/request_processor.cr:50:11 in 'process'
  from usr/share/crystal/src/http/server.cr:513:5 in 'handle_client'
  from usr/share/crystal/src/http/server.cr:468:13 in '->'
  from usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from usr/share/crystal/src/fiber.cr:92:34 in '->'
  from ???`

**Comment by w-le** [comment]
yep agreed, placeos/office365 should make multiple batch requests when required.
potential reference: https://github.com/acaprojects/ruby-engine-drivers/blob/beta/lib/microsoft/office2/client.rb#L140-L177

**Comment by camreeves** [comment]
Just fyi if you really want to go hardcore I'm pretty sure you can batch the batch requests.

**Comment by dukenguyenxyz** [comment]
we already handle batching the batch requests, the limit is just false, should be 20 when it is currently 50. this PR will resolve this https://github.com/PlaceOS/office365/pull/19 . please lmk if I got anything wrong.

**Comment by pkheav** [comment]
thanks @dukeraphaelng , yeah this is fixed now
